name: Notify on Pull Request

on:
  workflow_dispatch:
  # pull_request:
  #   branches: [main]
    # types: create

jobs:          
  get_message:
    runs-on: windows-latest
    permissions:
      # this permission should be set to be able use secrets.GITHUB_TOKEN
      id-token: write
      # not sure if this permission is necessary, just didn't try to remove it when testing
      contents: read
      # this permission should be set to be able get commits data by curl request
      pull-requests: read
    steps:
      - name: Get commits via cURL
        env:
          # github URL to list commits
          COMMITS_URL: ${{ github.event.pull_request.commits_url }}
        run: |
          echo ${COMMITS_URL}
         # if ("${COMMITS_URL}")
            # get commits list and pick up last one by jq
            # caution: only 100 commits will be taken by curl
            # if your PR has more than 100 commits you have to 
            # set page query parameter and request last page commits
            # API URL details: https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-commits-on-a-pull-request
         #   LAST_MSG=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${COMMITS_URL}?per_page=100" | jq -r .[-1].commit.message)
            # set environment variable
         #   echo "LAST_MSG=${LAST_MSG}" >> "${GITHUB_ENV}"
